# Generated by Django 5.2 on 2025-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoferramenta',
            options={'verbose_name': 'Configuração para levantamento de informações rep. origem, simulação de conflitos e execução da customização', 'verbose_name_plural': 'Configurações para levantamento de informações rep. origem, simulação de conflitos e execução da customização'},
        ),
        migrations.AlterModelOptions(
            name='configuracaogeral',
            options={'verbose_name': 'Configuração para comparação de projetos', 'verbose_name_plural': 'Configurações para comparação de projetos'},
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='descricao_client',
            field=models.CharField(default='', max_length=150, verbose_name='Descrição do repositório de produção'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='descricao_vendor',
            field=models.CharField(default='', max_length=150, verbose_name='Descrição do repositório mergeado '),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='path_repositorio_client',
            field=models.CharField(max_length=150, verbose_name='Caminho completo do repositório de produção'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='path_repositorio_vendor',
            field=models.CharField(max_length=150, verbose_name='Caminho completo do repositório mergeado'),
        ),
    ]
